version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
  db:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856 #(needed for db import)
    environment:
      MYSQL_DATABASE: 'nosdeputes'
      MYSQL_USER: 'nosdeputes'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data/sql:/data/sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
    ports:
      - '8081:80'
    expose:
      - '8081'

